# Generated by Django 3.0.8 on 2020-07-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='href',
            field=models.CharField(default='main', max_length=128, verbose_name='ссылка'),
        ),
    ]
